### input check with 3 words
POST https://sentiment-checker-backend.vercel.app/api/check
Content-Type: application/json 

{
    "words" : "apaan si lu anjing banget dah muke kek kontol gitu juga apa banget sii luh"
}
