### input check with 3 words
POST http://localhost:3000/api/check
Content-Type: application/json 

{
    "words" : "kontol memek anjing tes lu kontol banget tes kamu cantik sekali test kontol kamu lucu"
}

